### PR TITLE
make sure that $tree is instance of jQuery 

### PR DESCRIPTION
**Pull request by markovicdenis**

### CODE REVIEW

**Comment by sQu1rr** [comment]
Thanks mate will test and merge later this week. How come it worked before - or has it never worked?

**Comment by dcalhoun** [comment]
@sQu1rr this PR is to fix #15. It seems like the [Atom's `1.16.0` release](https://github.com/atom/atom/releases/tag/v1.16.0) may have introduced a change that causes this error. Specifically, maybe it's wrapped up in...

>Lots of progress in our ongoing effort to remove jQuery from bundled packages.

Now that `1.16.0` is an official release, nerd-treeview is all but unusable at the moment. Nearly every movement key throws an error. ☹️

**Comment by sQu1rr** [comment]
OK I will look into it in my free time. thanks for the PR i'll try not to delay merging it for too long

**Comment by jondot** [comment]
For `gg` and `G` (scroll to top and bottom) another fix is needed in `jumpLine`:

```coffeescript
    jumpLine: (num) ->
        return if not treeView = @getTreeView()

        $elements = $(treeView.element).find('li:visible')
        #                       ^---- here
        if not num
            num = if @num then @num else $elements.size()
            num = $elements.size() if num > $elements.size()

        $entry = $elements.eq(num - 1)
        treeView.selectEntry($entry[0])
        scrollIfInvisible($entry, treeView)

        @clearPrefix()
```

**Pull request merged**
